C:\Users\paras\anaconda3\envs\venv\Lib\site-packages\torch\nn\modules\loss.py:536: UserWarning: Using a target size (torch.Size([2])) that is different to the input size (torch.Size([2, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
Traceback (most recent call last):
  File "C:\Users\paras\PycharmProjects\DL_regression\main\main_cnn.py", line 45, in <module>
    trainer.train_and_evaluate(fold, config)
  File "C:\Users\paras\PycharmProjects\DL_regression\trainers\trainer.py", line 46, in train_and_evaluate
    loss.backward()
  File "C:\Users\paras\anaconda3\envs\venv\Lib\site-packages\torch\_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "C:\Users\paras\anaconda3\envs\venv\Lib\site-packages\torch\autograd\__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Found dtype Double but expected Float